name: loci
description: App Cardápio.



publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  google_fonts:
  numberpicker:
  tab_indicator_styler:
  flutter_credit_card:
  slimy_card:
  flutter_svg:
  flutter_fluid_slider:
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true
